'use strict';
const {DatabaseSync}=require('node:sqlite');
const {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash,createPublicKey,verify}=require('node:crypto');
const fs=require('node:fs'),path=require('node:path');
const hash=s=>createHash('sha256').update(s).digest('hex');
const token=()=>randomBytes(32).toString('hex');
function createAPI(directory){
 fs.mkdirSync(directory,{recursive:true});const db=new DatabaseSync(path.join(directory,'capmoney.sqlite'));db.exec(`PRAGMA journal_mode=WAL;
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,login TEXT UNIQUE NOT NULL,salt TEXT,password TEXT);
 CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,userId TEXT,expires INTEGER);
 CREATE TABLE IF NOT EXISTS books(id TEXT PRIMARY KEY,name TEXT,owner TEXT,data TEXT,revision INTEGER DEFAULT 0);
 CREATE TABLE IF NOT EXISTS members(bookId TEXT,userId TEXT,role TEXT,PRIMARY KEY(bookId,userId));
 CREATE TABLE IF NOT EXISTS invites(hash TEXT PRIMARY KEY,bookId TEXT,role TEXT,expires INTEGER);
 CREATE TABLE IF NOT EXISTS challenges(nonce TEXT PRIMARY KEY,expires INTEGER);
 CREATE TABLE IF NOT EXISTS quickkeys(hash TEXT PRIMARY KEY,bookId TEXT,userId TEXT,created INTEGER);
 CREATE TABLE IF NOT EXISTS quickrequests(keyhash TEXT,requestId TEXT,PRIMARY KEY(keyhash,requestId));`);
 const rates=new Map();const fail=(message,status=400)=>{const e=Error(message);e.status=status;throw e};
 const text=(v,max=100)=>typeof v==='string'&&v.trim()&&v.length<=max?v.trim():fail('Thông tin không hợp lệ.');
 function login(userId){const t=token();db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(t),userId,Date.now()+7*86400000);return {token:t,user:db.prepare('SELECT id,name FROM users WHERE id=?').get(userId)};}
 function user(req){const key=(req.headers.authorization||'').replace(/^Bearer /,'');if(!key)fail('Hãy đăng nhập.',401);const session=db.prepare('SELECT userId FROM sessions WHERE hash=? AND expires>?').get(hash(key),Date.now());if(!session)fail('Phiên đăng nhập đã hết hạn.',401);return session.userId;}
 function member(bookId,userId,write=false){const m=db.prepare('SELECT role FROM members WHERE bookId=? AND userId=?').get(bookId,userId);if(!m||write&&!['owner','editor'].includes(m.role))fail('Bạn không có quyền truy cập.',403);return m;}
 function ledger(data){if(!data||!Array.isArray(data.accounts)||!Array.isArray(data.transactions)||!Array.isArray(data.budgets))fail('Sổ không hợp lệ.');const ids=new Set();for(const a of data.accounts){text(a.id);text(a.name);if(ids.has(a.id)||!Number.isSafeInteger(a.opening))fail('Tài khoản không hợp lệ.');ids.add(a.id);}const tids=new Set();for(const t of data.transactions){text(t.id);if(tids.has(t.id)||!ids.has(t.account)||!['income','expense','transfer'].includes(t.type)||!Number.isSafeInteger(t.amount)||t.amount<=0||t.amount>1e14||!/^\d{4}-\d{2}-\d{2}$/.test(t.date)||isNaN(Date.parse(t.date))||typeof t.note!=='string'||t.note.length>500||typeof t.category!=='string'||t.type==='transfer'&&(!ids.has(t.to)||t.to===t.account))fail('Giao dịch không hợp lệ.');tids.add(t.id);}for(const b of data.budgets){text(b.id);text(b.name);if(!Number.isSafeInteger(b.amount)||b.amount<=0||!/^\d{4}-\d{2}$/.test(b.month))fail('Ngân sách không hợp lệ.');}return data;}
 async function body(req){let value='';for await(const chunk of req){value+=chunk;if(Buffer.byteLength(value)>2*1024*1024)fail('Dữ liệu vượt 2 MB.',413);}try{return value?JSON.parse(value):{}}catch{fail('JSON không hợp lệ.')}}
 async function handle(req,res,url){if(!url.pathname.startsWith('/api/'))return false;res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');const send=(v,status=200)=>{res.writeHead(status);res.end(JSON.stringify(v))};try{
  if(req.headers.origin&&req.headers.origin!==process.env.PUBLIC_ORIGIN&&req.headers.origin!==`http://${req.headers.host}`)fail('Nguồn yêu cầu không hợp lệ.',403);
  const route=url.pathname,method=req.method;const data=['POST','PUT','DELETE'].includes(method)?await body(req):{};
  if(route==='/api/config'){send({appleClientId:process.env.APPLE_CLIENT_ID||'',appleRedirect:process.env.APPLE_REDIRECT_URI||'',server:true});return true;}
  if(['/api/register','/api/login','/api/apple','/api/apple-challenge'].includes(route)){const ip=req.socket.remoteAddress;const rate=rates.get(ip)||{count:0,time:Date.now()};if(Date.now()-rate.time>60000){rate.count=0;rate.time=Date.now()}if(++rate.count>20)fail('Thử lại sau một phút.',429);rates.set(ip,rate);}
  if(route==='/api/register'&&method==='POST'){const name=text(data.name,60),loginName=text(data.login,80).toLowerCase(),password=text(data.password,200);if(password.length<10)fail('Mật khẩu cần ít nhất 10 ký tự.');if(db.prepare('SELECT id FROM users WHERE login=?').get(loginName))fail('Tên đăng nhập đã tồn tại.',409);const id=randomUUID(),salt=token();db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(id,name,loginName,salt,scryptSync(password,salt,64).toString('hex'));send(login(id),201);return true;}
  if(route==='/api/login'&&method==='POST'){const u=db.prepare('SELECT * FROM users WHERE login=?').get(text(data.login,80).toLowerCase());const candidate=scryptSync(text(data.password,200),u?.salt||'missing',64);if(!u?.password||!timingSafeEqual(candidate,Buffer.from(u.password,'hex')))fail('Tên đăng nhập hoặc mật khẩu không đúng.',401);send(login(u.id));return true;}
  if(route==='/api/apple-challenge'&&method==='POST'){if(!process.env.APPLE_CLIENT_ID)fail('Máy chủ chưa cấu hình đăng nhập Apple.',503);const nonce=token();db.prepare('INSERT INTO challenges VALUES(?,?)').run(nonce,Date.now()+300000);send({nonce});return true;}
  if(route==='/api/apple'&&method==='POST'){if(!process.env.APPLE_CLIENT_ID)fail('Máy chủ chưa cấu hình Apple.',503);const jwt=text(data.idToken,12000),parts=jwt.split('.');if(parts.length!==3)fail('Token Apple không hợp lệ.',401);const header=JSON.parse(Buffer.from(parts[0],'base64url')),claims=JSON.parse(Buffer.from(parts[1],'base64url'));if(header.alg!=='RS256'||claims.iss!=='https://appleid.apple.com'||claims.aud!==process.env.APPLE_CLIENT_ID||claims.exp<=Date.now()/1000||!claims.sub||!db.prepare('SELECT nonce FROM challenges WHERE nonce=? AND expires>?').get(claims.nonce||'',Date.now()))fail('Token Apple không hợp lệ.',401);const response=await fetch('https://appleid.apple.com/auth/keys');if(!response.ok)fail('Không lấy được khóa Apple.',502);const keys=await response.json(),key=keys.keys.find(k=>k.kid===header.kid);if(!key||!verify('RSA-SHA256',Buffer.from(parts[0]+'.'+parts[1]),createPublicKey({key,format:'jwk'}),Buffer.from(parts[2],'base64url')))fail('Chữ ký Apple không hợp lệ.',401);db.prepare('DELETE FROM challenges WHERE nonce=?').run(claims.nonce);const name='apple:'+claims.sub;let u=db.prepare('SELECT id FROM users WHERE login=?').get(name);if(!u){u={id:randomUUID()};db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(u.id,'Người dùng Apple',name,null,null)}send(login(u.id));return true;}
  if(route==='/api/quick'&&method==='POST'){const keyhash=hash((req.headers.authorization||'').replace(/^Bearer /,'')),key=db.prepare('SELECT * FROM quickkeys WHERE hash=?').get(keyhash);if(!key)fail('Khóa phím tắt không hợp lệ.',401);member(key.bookId,key.userId,true);const requestId=text(data.requestId,100);if(db.prepare('SELECT requestId FROM quickrequests WHERE keyhash=? AND requestId=?').get(keyhash,requestId)){send({duplicate:true});return true;}const b=db.prepare('SELECT * FROM books WHERE id=?').get(key.bookId),s=JSON.parse(b.data);const t={id:randomUUID(),type:data.type||'expense',amount:data.amount,account:data.account||s.accounts[0]?.id,to:data.to,category:data.category||'Khác',note:data.note||'Phím tắt',date:data.date||new Date().toISOString().slice(0,10)};s.transactions.push(t);ledger(s);db.exec('BEGIN');try{db.prepare('INSERT INTO quickrequests VALUES(?,?)').run(keyhash,requestId);db.prepare('UPDATE books SET data=?,revision=revision+1 WHERE id=?').run(JSON.stringify(s),b.id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}send({id:t.id});return true;}
  const userId=user(req);
  if(route==='/api/me'){send(db.prepare('SELECT id,name FROM users WHERE id=?').get(userId));return true;}
  if(route==='/api/logout'&&method==='POST'){db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(req.headers.authorization.replace(/^Bearer /,'')));send({ok:true});return true;}
  if(route==='/api/books'&&method==='GET'){send(db.prepare('SELECT b.id,b.name,b.revision,m.role FROM books b JOIN members m ON b.id=m.bookId WHERE m.userId=?').all(userId));return true;}
  if(route==='/api/books'&&method==='POST'){const id=randomUUID(),name=text(data.name),initial={accounts:[{id:randomUUID(),name:'Sổ chung',opening:0}],transactions:[],budgets:[]};db.exec('BEGIN');try{db.prepare('INSERT INTO books(id,name,owner,data) VALUES(?,?,?,?)').run(id,name,userId,JSON.stringify(initial));db.prepare('INSERT INTO members VALUES(?,?,?)').run(id,userId,'owner');db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}send({id},201);return true;}
  if(route==='/api/join'&&method==='POST'){const key=hash(text(data.code,100));const invite=db.prepare('SELECT * FROM invites WHERE hash=? AND expires>?').get(key,Date.now());if(!invite)fail('Mã mời đã dùng hoặc hết hạn.',404);db.exec('BEGIN');try{db.prepare('INSERT OR IGNORE INTO members VALUES(?,?,?)').run(invite.bookId,userId,invite.role);db.prepare('DELETE FROM invites WHERE hash=?').run(key);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}send({id:invite.bookId});return true;}
  const match=route.match(/^\/api\/books\/([^/]+)(?:\/(invite|members|quickkey))?$/);if(match){const [,id,part]=match;const membership=member(id,userId,method==='PUT');const b=db.prepare('SELECT * FROM books WHERE id=?').get(id);if(!b)fail('Không tìm thấy sổ.',404);
   if(part==='invite'&&method==='POST'){if(membership.role!=='owner')fail('Chỉ chủ sổ được mời.',403);const code=token();db.prepare('INSERT INTO invites VALUES(?,?,?,?)').run(hash(code),id,data.role==='viewer'?'viewer':'editor',Date.now()+86400000);send({code});return true;}
   if(part==='quickkey'&&method==='POST'){member(id,userId,true);const key=token();db.prepare('INSERT INTO quickkeys VALUES(?,?,?,?)').run(hash(key),id,userId,Date.now());send({key});return true;}
   if(part==='quickkey'&&method==='DELETE'){db.prepare('DELETE FROM quickkeys WHERE bookId=? AND userId=?').run(id,userId);send({ok:true});return true;}
   if(part==='members'&&method==='GET'){send(db.prepare('SELECT u.id,u.name,m.role FROM users u JOIN members m ON u.id=m.userId WHERE m.bookId=?').all(id));return true;}
   if(part==='members'&&method==='DELETE'){if(membership.role!=='owner'||data.userId===b.owner)fail('Không thể xóa thành viên này.',403);db.prepare('DELETE FROM members WHERE bookId=? AND userId=?').run(id,data.userId);db.prepare('DELETE FROM quickkeys WHERE bookId=? AND userId=?').run(id,data.userId);send({ok:true});return true;}
   if(!part&&method==='GET'){send({id,name:b.name,revision:b.revision,role:membership.role,data:JSON.parse(b.data)});return true;}
   if(!part&&method==='PUT'){ledger(data.data);const r=db.prepare('UPDATE books SET data=?,revision=revision+1 WHERE id=? AND revision=?').run(JSON.stringify(data.data),id,data.revision);if(!r.changes)fail('Sổ đã được người khác thay đổi. Hãy tải lại trước khi sửa.',409);send({revision:data.revision+1});return true;}
  }
  fail('Không tìm thấy chức năng.',404);
 }catch(e){send({error:e.status?e.message:'Máy chủ không xử lý được yêu cầu.'},e.status||500);}return true;}
 return {handle,close:()=>db.close()};
}
module.exports={createAPI};
