(function(root){
 'use strict';
 const date=s=>new Date(s+'T12:00:00');
 const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 function advance(s,frequency,anchor){const d=date(s);if(frequency==='day')d.setDate(d.getDate()+1);else if(frequency==='week')d.setDate(d.getDate()+7);else {const day=anchor||d.getDate();d.setDate(1);d.setMonth(d.getMonth()+(frequency==='year'?12:1));d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));}return iso(d);}
 function interest(s,at){const end=at<s.maturity?at:s.maturity;const days=Math.max(0,Math.round((date(end)-date(s.start))/86400000));return Math.round(s.principal*s.rate/100*days/365);}
 function split(total,members){if(!Number.isSafeInteger(total)||total<1||members.length<1||new Set(members).size!==members.length)throw Error('Số tiền hoặc thành viên không hợp lệ.');return members.map((member,i)=>({member,amount:Math.floor(total/members.length)+(i<total%members.length?1:0)}));}
 function settlements(bills,payments){const balances={};for(const b of bills){balances[b.payer]=(balances[b.payer]||0)+b.total;for(const share of b.shares)balances[share.member]=(balances[share.member]||0)-share.amount;}for(const p of payments){balances[p.from]=(balances[p.from]||0)+p.amount;balances[p.to]=(balances[p.to]||0)-p.amount;}const debtors=Object.entries(balances).filter(x=>x[1]<0).map(([id,n])=>({id,n:-n}));const creditors=Object.entries(balances).filter(x=>x[1]>0).map(([id,n])=>({id,n}));const result=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const n=Math.min(debtors[i].n,creditors[j].n);result.push({from:debtors[i].id,to:creditors[j].id,amount:n});if(!(debtors[i].n-=n))i++;if(!(creditors[j].n-=n))j++;}return result;}
 function due(s,until){const next=structuredClone(s);let count=0;for(const r of next.recurring||[]){let n=0;while(r.active&&r.next<=until&&(!r.end||r.next<=r.end)){if(++n>2000)throw Error('Lịch quá dài; hãy sửa ngày bắt đầu.');const id=`rec-${r.id}-${r.next}`;if(!next.transactions.some(t=>t.id===id)){next.transactions.push({id,type:r.type,amount:r.amount,account:r.account,category:r.category,date:r.next,note:r.name,recurringId:r.id,image:null});count++;}r.next=advance(r.next,r.frequency,r.anchor);}}return {state:next,count};}
 function parseReceipt(text){const lines=text.split(/\r?\n/),candidates=[];for(const line of lines){if(/số dư|so du|balance|tài khoản|tai khoan|account|phí|fee/i.test(line)&&!/số tiền|so tien|amount/i.test(line))continue;const re=/(\d{1,3}(?:[.,\s]\d{3})+|\d{4,14})\s*(?:đ|₫|vnd|vnđ)?/gi;for(const m of line.matchAll(re)){const amount=Number(m[1].replace(/\D/g,''));if(amount>0&&Number.isSafeInteger(amount))candidates.push({amount,score:/số tiền|so tien|amount|tổng|tong|total|thanh toán|thanh toan/i.test(line)?2:/vnd|vnđ|₫|đ/i.test(line)?1:0});}}candidates.sort((a,b)=>b.score-a.score);return {amount:candidates[0]?.amount||0,note:text.slice(0,200)};}
 root.Finance={advance,interest,split,settlements,due,parseReceipt};
 if(typeof module!=='undefined')module.exports=root.Finance;
})(globalThis);
